name: Docker Image Build Prod Version

on:
  push:
    branches: [ "Production" ]
  pull_request:
    branches: [ "Production" ]

jobs:
  
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag rph-website:prod
        docker tag rph-website:prod 192.168.1.140:5000/rph-website:prod
        docker push 192.168.1.140:5000/rph-website:prod
      
