name: Docker Image Build Dev Version

on:
  push:
    branches: [ "Dev" ]

jobs:
  
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag rph-website:dev
        docker tag rph-website:dev 192.168.1.140:5000/rph-website:dev
        docker push 192.168.1.140:5000/rph-website:dev
      
    - name: ntfy-failed-notifications
      uses: niniyas/ntfy-action@master
      if: failure()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 5
        tags: +1,partying_face,action,failed
        details: Workflow has failed!
  
    - name: ntfy-success-notifications
      uses: niniyas/ntfy-action@master
      if: success()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 3
        tags: +1,partying_face,action,successfully,completed
        details: Workflow has been successfully completed!
  
    - name: ntfy-cancelled-notifications
      uses: niniyas/ntfy-action@master
      if: cancelled()
      with:
        url: '${{ secrets.NTFYURL }}'
        topic: '${{ secrets.NTFYTOPIC }}'
        priority: 3
        tags: +1,partying_face,action,cancelled
        details: Workflow has been cancelled!