name: Docker Image Build Dev Version

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag rph-website:dev
        docker tag rph-website:dev 192.168.1.140:5000/rph-website:dev
        docker push 192.168.1.140:5000/rph-website:dev
      
